import { Appointment, DarkModeTheme, FamilyMember, AlertItem, HealthRecord, UserProfile } from '../types';

export const COLORS = {
  primary: '#5E8FC0',
  primaryDk: '#3D6E9F',
  secondary: '#7CC9BE',
  accent: '#59B98A',
  success: '#2FBF71',
  warn: '#F4B740',
  danger: '#E45454',
  purple: '#6B7FD4',
  bg: '#F8FAFC',
  card: '#FFFFFF',
  textMain: '#1E3A5F',
  textSub: '#64748B',
};

export const getDarkModeTheme = (isDark: boolean): DarkModeTheme => {
  if (isDark) {
    return {
      bg: '#0F172A',
      card: '#1E293B',
      text: '#F1F5F9',
      sub: '#94A3B8',
      border: '#334155',
      inputBg: '#0F172A',
      isDark: true,
    };
  }
  return {
    bg: '#F8FAFC',
    card: '#FFFFFF',
    text: '#1E3A5F',
    sub: '#64748B',
    border: '#E2E8F0',
    inputBg: '#F8FAFC',
    isDark: false,
  };
};

export const INITIAL_USER: UserProfile = {
  name: 'Antônio Carlos Silva',
  cpf: '123.456.789-00',
  phone: '(11) 98765-4321',
  birthDate: '14/05/1962 (64 anos)',
  susCard: '898 0012 3456 7890',
  userType: 'Paciente',
  bloodType: 'O+',
  emergencyContact: {
    name: 'Ana Maria Silva (Filha)',
    phone: '(11) 99888-7766',
    relation: 'Familiar Responsável',
  },
  conditions: ['Hipertensão Estágio 1', 'Diabetes Tipo 2', 'Sedentarismo Moderado'],
  medications: [
    { name: 'Losartana Potássica', dosage: '50mg', frequency: '1x ao dia (Manhã)', nextTime: '08:00' },
    { name: 'Metformina', dosage: '850mg', frequency: '2x ao dia (Almoço e Jantar)', nextTime: '12:30' },
    { name: 'Sinvastatina', dosage: '20mg', frequency: '1x ao dia (Noite)', nextTime: '21:00' },
  ],
};

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 1,
    doctor: 'Dra. Beatriz Mendes',
    specialty: 'Cardiologia SUS',
    date: '2026-09-02',
    time: '09:30',
    type: 'presencial',
    status: 'confirmed',
    location: 'UBS Vila Mariana - Sala 04',
    bookedBy: 'Ana Silva (Filha / Cuidadora)',
    notes: 'Trazer exames recentes de sangue e histórico de pressão dos últimos 30 dias.',
  },
  {
    id: 2,
    doctor: 'Dr. Fernando Oliveira',
    specialty: 'Endocrinologista',
    date: '2026-09-08',
    time: '14:00',
    type: 'teleconsulta',
    status: 'pending',
    location: 'Teleconsulta Conecte SUS',
    bookedBy: 'Antônio Silva',
    notes: 'Avaliação de ajuste de dosagem da Metformina e curva glicêmica matinal.',
  },
  {
    id: 3,
    doctor: 'Dra. Camila Ribeiro',
    specialty: 'Nutrição Clínica',
    date: '2026-08-20',
    time: '10:00',
    type: 'presencial',
    status: 'completed',
    location: 'Ambulatório Central de Especialidades',
    bookedBy: 'Antônio Silva',
    notes: 'Plano alimentar adaptado para controle glicêmico e redução de sódio.',
  },
];

export const INITIAL_FAMILY: FamilyMember[] = [
  {
    id: 'f1',
    name: 'Antônio Silva',
    relation: 'Titular',
    role: 'Você',
    phone: '(11) 98765-4321',
    avatarBg: '#5E8FC0',
    initials: 'AS',
    status: 'online',
    lastSeen: 'Ativo agora',
  },
  {
    id: 'f2',
    name: 'Ana Maria Silva',
    relation: 'Filha & Cuidadora',
    role: 'Familiar',
    phone: '(11) 99888-7766',
    avatarBg: '#59B98A',
    initials: 'AM',
    status: 'online',
    lastSeen: 'Visto há 5 min',
  },
  {
    id: 'f3',
    name: 'Dr. Lucas Ferreira',
    relation: 'Médico da Família (UBS)',
    role: 'SUS',
    phone: '(11) 3210-9900',
    avatarBg: '#6B7FD4',
    initials: 'LF',
    status: 'away',
    lastSeen: 'Disponível das 08h às 17h',
  },
  {
    id: 'f4',
    name: 'Enf. Juliana Castro',
    relation: 'Agente Comunitária de Saúde',
    role: 'SUS',
    phone: '(11) 3210-9911',
    avatarBg: '#7CC9BE',
    initials: 'JC',
    status: 'online',
    lastSeen: 'Em campo',
  },
];

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'alt1',
    title: 'Horário do Medicamento',
    desc: 'Tomar 1 comp. de Losartana 50mg com água após o café da manhã.',
    type: 'info',
    date: 'Hoje',
    time: '08:00',
    emoji: '💊',
    color: '#5E8FC0',
    actionLabel: 'Confirmar tomada',
  },
  {
    id: 'alt2',
    title: 'Atenção com a Glicemia',
    desc: 'Última medição (138 mg/dL) esteve ligeiramente acima da meta pré-refeição.',
    type: 'warn',
    date: 'Ontem',
    time: '19:40',
    emoji: '⚠️',
    color: '#F4B740',
    actionLabel: 'Ver histórico',
    actionScreen: 'glucose',
  },
  {
    id: 'alt3',
    title: 'Consulta em 2 dias',
    desc: 'Cardiologia SUS com Dra. Beatriz Mendes na UBS Vila Mariana.',
    type: 'info',
    date: '28 Ago',
    time: '10:00',
    emoji: '📅',
    color: '#59B98A',
    actionLabel: 'Ver detalhes',
    actionScreen: 'appointments',
  },
  {
    id: 'alt4',
    title: 'Pico de Pressão Detectado',
    desc: 'Pressão registrada em 142/92 mmHg. Recomenda-se repousar 15min e aferir novamente.',
    type: 'danger',
    date: '25 Ago',
    time: '16:15',
    emoji: '🚨',
    color: '#E45454',
    actionLabel: 'Registrar nova',
    actionScreen: 'pressure',
  },
];

export const INITIAL_RECORDS: HealthRecord[] = [
  {
    id: 'rec1',
    date: 'Hoje, 31 Ago',
    time: '07:30',
    systolic: 124,
    diastolic: 82,
    glucose: 104,
    heartRate: 72,
    mealContext: 'before',
    notes: 'Aferição em jejum, sentindo-se bem.',
    status: 'normal',
  },
  {
    id: 'rec2',
    date: 'Ontem, 30 Ago',
    time: '19:45',
    systolic: 128,
    diastolic: 84,
    glucose: 138,
    heartRate: 76,
    mealContext: 'after',
    notes: '2 horas após o jantar leve.',
    status: 'warn',
  },
  {
    id: 'rec3',
    date: '29 Ago',
    time: '08:00',
    systolic: 122,
    diastolic: 80,
    glucose: 98,
    heartRate: 70,
    mealContext: 'before',
    notes: 'Caminhada matinal de 20 minutos concluída.',
    status: 'normal',
  },
  {
    id: 'rec4',
    date: '28 Ago',
    time: '18:15',
    systolic: 136,
    diastolic: 88,
    glucose: 118,
    heartRate: 80,
    mealContext: 'after',
    notes: 'Dia mais agitado no trabalho artesanal.',
    status: 'warn',
  },
  {
    id: 'rec5',
    date: '27 Ago',
    time: '07:45',
    systolic: 120,
    diastolic: 78,
    glucose: 96,
    heartRate: 68,
    mealContext: 'before',
    notes: 'Pressão e glicemia excelentes.',
    status: 'normal',
  },
  {
    id: 'rec6',
    date: '26 Ago',
    time: '20:00',
    systolic: 142,
    diastolic: 92,
    glucose: 145,
    heartRate: 84,
    mealContext: 'after',
    notes: 'Consumo de alimento mais temperado no almoço.',
    status: 'danger',
  },
  {
    id: 'rec7',
    date: '25 Ago',
    time: '07:30',
    systolic: 125,
    diastolic: 82,
    glucose: 102,
    heartRate: 71,
    mealContext: 'before',
    notes: 'Rotina de remédios 100% em dia.',
    status: 'normal',
  },
];

export const SPECIALTIES = [
  'Cardiologia SUS',
  'Endocrinologia',
  'Clínica Geral UBS',
  'Nutrição Clínica',
  'Oftalmologia',
  'Enfermagem',
  'Geriatria',
  'Nefrologia',
];

export const HEALTH_LOCATIONS = [
  { id: 'loc1', name: 'UBS Vila Mariana', address: 'Rua Domingos de Morais, 2100' },
  { id: 'loc2', name: 'Ambulatório Médico de Especialidades (AME)', address: 'Av. Paulista, 1500' },
  { id: 'loc3', name: 'Hospital Municipal Integrado', address: 'Rua Vergueiro, 800' },
  { id: 'loc4', name: 'Centro de Saúde da Família Norte', address: 'Av. Santos Dumont, 450' },
];
